language: scala
jdk:
- oraclejdk7
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- git clone https://github.com/CommBank/ci.git
- chmod ugo+x ci/*
- ci/sbt-setup.sh
- ci/sbt-setup-version.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; test; package; scripted'
- ci/sbt-deploy-ivy.sh
after_script:
- rm -rf ci
- find $HOME/.ivy2 -name "*uniform*" -delete
env:
  global:
    secure: hxBTk+wXhsS+kDbYDCumkrecbiKlSjnzqRLcR86BbYpCoqlkepyj7Uu6rPwDLbXEV5Xtz7TfyFm6Q9yN30FtVh/foa7INz3DEOk6b9arJDnn602EUPZmC07N0GO9Zj2bsyjlDMOH0tJGIWGnsf03Hra5Lbvbv9x0IxaYPI4kxVo=
