language: scala
jdk:
- oraclejdk7
sudo: false
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- git clone https://github.com/CommBank/ci.git
- chmod ugo+x ci/*
- ci/sbt-setup.sh
- ci/sbt-setup-version.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; test; package; scripted' && ci/sbt-deploy-ivy.sh
  && ci/gh-pages.sh
after_script:
- rm -rf ci
- find $HOME/.ivy2 -name "*uniform*" -delete
env:
  global:
  - secure: GPsC7QFWTy+yJ0jYvqF3XOMNJ2nuiUL3QUZ/i5cbdrF9FEn2uf3dP6HjZBQs6sPdIAcE34aiu64AMp3hP6bkwltVGFJMRprXBEguBDUHWE4BQoqjoPcd9OyOwVymLnytZYbachGCCCLZ6q84sIaaEyPy6CVNSy4QNScO1eDEBB4=
  - secure: gmVdhlmQpdAGMLlBzSns6RFsjat7ztPsHZ2L43HeS1S11vjD7DOuewvYO0xcpJh+3l1bPaJEzioMVkn9d0w/gMJec0WxBokIvlD7Fi9LA7Rjc0uxSU+3K5dOyo9+aedt+dKGa/7YZv2qdSsyNYuwk5i39dgNsaBJ6/dh4BwonY0=
